import React from 'react';
import Link from 'next/link';
import { ArrowLeft, AlertTriangle } from 'lucide-react';
import { CLINIC_DATA } from '@/lib/clinic-data';

export const metadata = {
  title: "Medical Disclaimer | DIGISMILE Dental Clinic Puducherry",
  description: "Medical disclaimer regarding dental health information, online triage, and AI receptionist at DIGISMILE Dental Clinic Puducherry.",
};

export default function MedicalDisclaimerPage() {
  return (
    <div className="bg-white min-h-screen pb-24 font-sans text-gray-900">
      <div className="max-w-4xl mx-auto px-6 py-12 space-y-10">
        
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-sm font-semibold text-gray-500 hover:text-gray-900 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" /> Back to Home
        </Link>

        <div className="border-b border-gray-100 pb-8 space-y-4">
          <span className="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-red-600 bg-red-50 px-3 py-1.5 rounded-full">
            Medical & Clinical Advisory
          </span>
          <h1 className="text-3xl sm:text-5xl font-semibold tracking-tight text-gray-900">
            Medical & Dental Disclaimer
          </h1>
          <p className="text-sm font-medium text-gray-500">
            DIGISMILE DENTAL CLINIC, No 58, Muthu Mariamman Kovil St, Heritage Town, Heritage Town, Puducherry
          </p>
        </div>

        <div className="bg-gray-50 border border-gray-100 rounded-[2rem] p-8 sm:p-12 shadow-[0_8px_30px_rgb(0,0,0,0.04)] space-y-8 text-sm font-medium text-gray-700 leading-relaxed">
          
          <div className="p-6 bg-red-50 rounded-2xl flex items-start gap-4">
            <AlertTriangle className="w-6 h-6 text-red-600 shrink-0 mt-0.5" />
            <div className="text-sm text-gray-900 font-semibold leading-relaxed">
              The informational material published on this website and responses generated by our virtual receptionist &ldquo;PSandhosh&rdquo; are designed for general patient guidance, appointment coordination, and educational purposes only. They do not constitute formal medical diagnosis or prescription.
            </div>
          </div>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900">
              1. Need for In-Person Clinical Examination
            </h2>
            <p>
              Accurate dental diagnosis requires physical in-person clinical examination, dental probing, vitality testing, and high-resolution radiographic imaging (digital RVG) conducted by licensed dental surgeons such as Dr. Sandhosh or Dr. Sandhosh at our clinical facility.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900">
              2. Virtual Assistant &ldquo;PSandhosh&rdquo; Advisory
            </h2>
            <p>
              PSandhosh is an automated front-desk assistant configured with clinic operational details (hours, address, pricing guidelines, doctor credentials). She is not a physician and does not diagnose disease or prescribe analgesics, antibiotics, or treatments. In any situation involving severe acute pain, swelling, or trauma, PSandhosh is programmed to immediately direct you to contact our human clinical team directly.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900">
              3. Acute Dental Emergencies
            </h2>
            <p>
              If you are experiencing severe difficulty breathing, facial swelling spreading to the eye or neck, or uncontrollable bleeding, please proceed immediately to the nearest hospital casualty or call our emergency desk at <strong>{CLINIC_DATA.phone}</strong>.
            </p>
          </section>

        </div>
      </div>
    </div>
  );
}
